### ISSUE TITLE
FizzBuzz implementation

### ISSUE THREAD

**Issue by hajdumozes** [hajdumozes/fizzbuzz#1]
### Subtask:

- [x] Test service logic (FizzBuzzServiceImplTest)
- [x] Controller endpoint creation
- [x] Service logic implementation
- [x] Simple html which connects to the controller endpoint
