### ISSUE TITLE
Build and documentation

### ISSUE THREAD

**Issue by hajdumozes** [hajdumozes/fizzbuzz#4]
### Tasks

- [x] check if design documentations are present as requested
- [x] document how to build, test, and run the application
- [x] building a war file
- [x] testing the war file
- [x] make tests run during build
